portfolio/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'

  resources :thumb, :path => 'api/thumbs',
            only: [:index, :create, :show, :destroy]

  resources :projects

  get    'api/projects'     => 'projects#api_index'
  post   'api/projects'     => 'projects#api_create'
  get    'api/projects/:id' => 'projects#api_show'
  delete 'api/projects/:id' => 'projects#api_destroy'
  put    'api/projects/:id' => 'projects#api_update'
  get    'api/projects/:id/count_up' => 'projects#api_count_up'
end

portfolio/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :thumb
  validates :title, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :url, length: { maximum: 255 }
  validates :thumb_id, presence: true
end

portfolio/app/models/thumb.rb
class Thumb < ActiveRecord::Base
  has_one :project
  validates :file, presence: true
end

portfolio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  def hello
    render text: "hello, world!"
  end
end

portfolio/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

# web-view functions
  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    # TODO: api_createと共通化を図ったほうがいい
    input = params.require(:project).permit(:url, :title, :description, :thumb)

    # thumbを登録する
    unless input[:thumb]
      flash.now[:danger] = "Thumbnail is not specified"
      return render 'new'
    end
    thumb = Thumb.create({file: input[:thumb].read})

    # TODO: 例外処理がうまくいっていない
    # 下のunlessでパラメータエラーを補足すべきだが、Project.newの時点で例外を吐く
    project = Project.new({
                title: input[:title],
                url: input[:url],
                description: input[:description],
                thumb_id: thumb[:id],
                link_count: 0
              })

    unless project.valid?
      flash.now[:danger] = "Invalid params"
      return render 'new'
    end
    unless project.save
      flash.now[:danger] = "Failed to save the project"
      return render 'new'
    end
    flash[:success] = "The project is created."
    return redirect_to project
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to projects_url
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    # FIXME: thumbの扱いが考慮されていない
    # 要素を空で実行すると，その要素は更新されない
    # titleなど，入力必須の項目を空にしても普通に処理は成功する
    # MEMO: replace的な処理にする場合は、idの他にlink_countも引き継ぐ必要あり
    project = Project.find(params[:id])
    input = params.require(:project).
            permit(:url, :title, :description, :thumb)
    project.update(input)
    redirect_to project_path(project)
  end

# API functions
  def api_index
    render json: Project.all
  end

  def api_show
    project = Project.find_by(id: params[:id])
    return head :not_found unless project
    return render json: project
  end

  def api_create
    input = params.permit(:url, :title, :description, :thumb)

    # thumbを登録する
    return head :bad_request unless input[:thumb]
    thumb = Thumb.create({file: input[:thumb].read})

    project = Project.new({
                title: input[:title],
                url: input[:url],
                description: input[:description],
                thumb_id: thumb[:id],
                link_count: 0
              })

    return head :bad_request           unless project.valid?
    return head :internal_server_error unless project.save
    return render json: project
  end

  def api_destroy
    project = Project.find_by(id: params[:id])
    return head :not_found unless project

    project.destroy
    return render json: {msg: "Project" + params[:id] + " was deleted"}
  end

  def api_update
    # FIXME: thumbの扱いが考慮されていない
    project = Project.find_by(id: params[:id])
    return head :not_found unless project
    input = params.permit(:url, :title, :description, :thumb)
    project.update(input)
    return render json: project
  end

  def api_count_up
    # FIXME: カウントアップでupdated_atが更新されるのイケてない
    project = Project.find_by(id: params[:id])
    return head :not_found unless project
    project.update({link_count: project[:link_count] + 1})
    render json: project

    # api_updateが差分更新する仕様で確定なのであれば、このAPIを個別実装せずに
    # updateで代用してもいいかもしれない
  end
end

portfolio/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

portfolio/app/controllers/thumb_controller.rb
class ThumbController < ApplicationController
  def index
    thumbs = Thumb.all
    id_list = thumbs.map {|t| t[:id]}
    return render json: {thumbs: id_list}
  end

  def show
    thumb = Thumb.find(params[:id])
    send_data thumb.file, :type => 'image/jpeg', :disposition => 'inline'
  end

  def create
    file = params.permit(:file)[:file]
    return head :bad_request unless file
    thumb = Thumb.create({file: file.read})
    return render json: {id: thumb[:id]}
  end

  def destroy
    file = Thumb.find_by(id: params[:id])
    return head :not_found unless file

    file.destroy
    return render json: {msg: "Thumb" + params[:id] + " was deleted"}
  end
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/projects_helper.rb
module ProjectsHelper
end

portfolio/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

portfolio/app/helpers/thumb_helper.rb
module ThumbHelper
end

portfolio/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This site is a challenge for <a href="https://app.code-check.io/">codecheck</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Help",   help_path %></li>
      <li><%= link_to "Repository", "https://github.com/medalhkr/codecheck-1908" %>
      </li>
    </ul>
  </nav>
</footer>

portfolio/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "portfolio", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All", projects_path %></li>
        <li><%= link_to "New", new_project_path %></li>
      </ul>
    </nav>
  </div>
</header>

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

portfolio/app/views/projects/_count_up.html.erb
<%= javascript_tag do %>

$(".project_link").each(function() {
  var pid = $(this).attr("data-project-id");
  $(this).click(function() {
    $.ajax({
        type: 'GET',
        url: '<%= api_projects_path %>/' + pid + '/count_up'
    });
  });
});

<% end %>

portfolio/app/views/projects/_list.html.erb
<article>
  <section class="project_info container">
    <div class="row">

      <div class="thumb col-md-3">
        <%= link_to image_tag(thumb_path(project.thumb_id)), project_path(project) %>
      </div>

      <div class="text_info col-md-9">
        <div class="title">
          <span class="count"><%= project.link_count %> views</span>
          <h1 class="page-header"> <%= project.title %> </h1>
          <%= link_to project.url, project.url, class: "project_link",
                data: {project_id: project.id} %>
        </div>
        <div class="description">
          <%= project.description %>
        </div>
      </div>
    </div>
  </section>
</article>

portfolio/app/views/projects/edit.html.erb
<h1>edit project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <br>

      <%= f.label :url %>
      <%= f.url_field :url, class: 'form-control' %>
      <br>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      <br>

      <% # f.label :thumb %>
      <% # f.file_field :thumb, accept: "image/jpeg" %>
      <br>

      <%= f.submit "Update the project", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

portfolio/app/views/projects/index.html.erb
<div id="projects-view">


<section class="header">
  <h1>project list</h1>
</section>


<article class="view container">
  <% @projects.each do |project| %>
    <%= render partial: "projects/list", locals: { project: project } %>
  <% end %>
</article>


<section class="footer">

</section>

<%= render partial: "projects/count_up" %>
</div>

portfolio/app/views/projects/new.html.erb
<h1>new project</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@project) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <br>

      <%= f.label :url %>
      <%= f.url_field :url, class: 'form-control' %>
      <br>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
      <br>

      <%= f.label :thumb %>
      <%= f.file_field :thumb, accept: "image/jpeg" %>
      <br>

      <%= f.submit "Create new project", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

portfolio/app/views/projects/show.html.erb
<article id="project-detail">


<section class="header container">
<div class="row">

  <div class="col-md-3 thumb">
    <%= link_to image_tag(thumb_path(@project.thumb_id)), project_path(@project) %>
  </div>

  <div class="col-md-9 text_info">
    <div class="title">
      <span class="count"><%= @project.link_count %> views</span>
      <h1 class="page-header"> <%= @project.title %> </h1>
      <%= link_to @project.url, @project.url, class: "project_link",
          data: {project_id: @project.id} %>
    </div>
    <div class="padding"></div>
    <div class="modify">
      <%= link_to "edit", edit_project_path(@project), class: "edit" %>
      <%= link_to "delete", project_path(@project),
                      method: :delete, class: "delete", 
                      data: { confirm: "You sure?" } %>
    </div>
  </div>

</div>
</section>



<section class="contents">
  <div class="page-header"><h3>description</h3></div>

  <div class="description">
    <%= @project.description %>
  </div>
</section>

<%= render partial: "projects/count_up" %>
</article>

portfolio/app/views/shared/_project.erb
<article>
  <section class="project_info">
    <%= link_to project.title, projects_path + '/' + project.id.to_s %>
    <%= text_area_tag nil, project.description, :readonly => true,
            :size => detail ? "60x10" : "60x5" %>
    <%= link_to project.url, project.url, class: "url" %>
    <% if detail %>
      <br>
      <!-- FIXME: path -->
      <%= link_to "delete", projects_path + '/' + project.id.to_s,
                        method: :delete, class: "delete", 
                        data: { confirm: "You sure?" } %>
      <%= link_to "edit", edit_project_path(project), class: "edit" %>
    <% end %>
  </section>
</article>

portfolio/app/views/shared/_project.html.erb
<article>
  <section class="project_info container">
    <div class="row">
      <div class="thumb col-md-3">
        <%= link_to image_tag(thumb_path(project.thumb_id)),
                  project_path(project) %>
      </div>
      <div class="text_info col-md-9">
        <h1 class="page-header"> <%= project.title %> </h1>
        <%= link_to project.url, project.url, class: "url" %>
        <%= text_area_tag nil, project.description, :readonly => true,
                :size => detail ? "60x10" : "60x5" %>
      </div>
    </div>
  </section>
  <% if detail %>
    <div class="modify">
      <%= link_to "delete", project_path(project),
                        method: :delete, class: "delete", 
                        data: { confirm: "You sure?" } %>
      <%= link_to "edit", edit_project_path(project), class: "edit" %>
    </div>
  <% end %>
</article>

portfolio/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

portfolio/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

portfolio/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

portfolio/app/views/thumb/index.html.erb
<h1>Thumb#index</h1>
<p>Find me in app/views/thumb/index.html.erb</p>

portfolio/app/views/thumb/show.html.erb
<h1>Thumb#show</h1>
<p>Find me in app/views/thumb/show.html.erb</p>